### ISSUE TITLE
Error on plugin loading

### ISSUE THREAD

**Issue by Wizardon777** [onebone/ArtificialIntelligent#11]
**Server:** Genisys 1a4abbc
**OS:** Windows 10 Pro x64
**Other plugins:** essentialsTP 1.0.9; DevTools 1.10.0; LiveXYZ 0.5.0-alpha; SimpleAuth 1.7.2; SimpleAuthHelper 2.0.4

**Error:**
`Error: Cannot use pocketmine\nbt\tag\Float as Float because 'Float' is a special class name
File: /ArtificialIntelligent_v0.1.phar/src/onebone/artificialintelligent/ArtificialIntelligent
Line: 10
Type: E_COMPILE_ERROR`

Any suggestions?

**Comment by inxomnyaa** [comment]
PHP5

**Comment by Wizardon777** [comment]
I'm using PHP7, you mean it will not work for me?

**Comment by inxomnyaa** [comment]
Well. clearsky maybe

**Comment by Wizardon777** [comment]
In clearsky I get api error.

`[Server thread/ERROR]: Could not load plugin 'ArtificialIntelligent': Plugin has a too new minor API version. Check pocketmine.yml settings.`

**Comment by inxomnyaa** [comment]
> Check pocketmine.yml settings.

set plugins minor and so on all to true

**Comment by onebone** [comment]
I no longer maintain this project.

https://github.com/milk0417/PureEntities may be an alternative. Also deprecated, though.
