### ISSUE TITLE
how to dowload it

### ISSUE THREAD

**Issue by lolcraftboy14** [onebone/ArtificialIntelligent#5]
how can a dowload it

**Comment by inxomnyaa** [comment]
Not really..
Is that really your question? You download it like every PocketMine Plugin..

**Comment by lolcraftboy14** [comment]
The forem pocketmine  ofline

**Comment by MarcoDiGio** [comment]
http://forums.pocketmine.net isn't offline.

**Comment by onebone** [comment]
https://onebone.me/plugins/#artificialintelligent

I didn't have uploaded this plugin to forum.
